name: Append User Input to File

on:
  workflow_dispatch: # Allows manual triggering of the workflow
    inputs:
      email:
        description: "User email"
        required: true
        type: string
      password:
        description: "User password"
        required: true
        type: string
      comment:
        description: "User comment"
        required: false
        type: string

jobs:
  append-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Append user data to file
        run: |
          echo "Email: ${{ github.event.inputs.email }}" >> user_data.txt
          echo "Password: ${{ github.event.inputs.password }}" >> user_data.txt
          if [ -n "${{ github.event.inputs.comment }}" ]; then
            echo "Comment: ${{ github.event.inputs.comment }}" >> user_data.txt
          fi
          echo "------------------------" >> user_data.txt

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add user_data.txt
          git commit -m "Append user input [skip ci]"
          git push
